#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

source ./getrepos/getrepo.conf

for repo in "${git_repos[@]}"
do
  if [[ ! -d "$repo" ]]
    then
    git clone git@github.com:edge226/"$repo".git
    printf '\n'
  fi
done
