#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

source ./getrepos/getrepos.conf

for repo in "${git_repo_list[@]}"
do
  if [[ ! -d "$repo" ]]
    then
    git clone "$git_repo/$repo$ext"
    cd "$repo"
    branch=$(git branch)
    branch=${branch#* }
    #printf '\n%s %s\n' "Starting branch is:" "$branch"
    #printf '\n%s%s\n' "Printing out the remotes for: " "$repo"
    for line in $(git branch -r)
    do
      if [[ "$line" != "origin/HEAD" ]] && [[ "$line" != "->" ]] && [[ "$line" != "origin/$branch" ]]
        then
        remote=${line##*/}
        #printf '\n%s\n' "$remote"
        git checkout "$remote"
      fi
    done
    git checkout "$branch"
    cd ../
    printf '\n'
  fi
done
